# 1. Dataset:

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import recall_score, precision_score, accuracy_score

In [2]:
from sklearn.datasets import load_iris

In [3]:
data = load_iris()

In [4]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
dataset = pd.DataFrame(data['data'])

In [6]:
dataset.columns = ['sepal length',
  'sepal width',
  'petal length',
  'petal width']

In [7]:
dataset['variety'] = data['target']

In [8]:
dataset.head(5)

sepal length  sepal width  petal length  petal width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [9]:
dataset = dataset.drop_duplicates()
dataset

sepal length  sepal width  petal length  petal width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2          2.0        2
148           6.2          3.4           5.4          2.3        2
149           5.9          3.0           5.1          1.8        2

[149 rows x 5 columns]

In [10]:
from sklearn.model_selection import train_test_split
X = dataset.drop('variety', axis=1)
y = dataset['variety']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state = 2022)

# 2. Implementation:

In [11]:
def distance(point1, point2):
    dimentionality = len(point1)
    dist = 0
    
    for i in range(dimentionality):
        dist += (point1[i] - point2[i])**2
        
    dist = dist**(0.5)
    return dist

def dist_array(point, X, y):
    arr = []
    inv_dist = []
    
    
    for i, p in enumerate(X):
        arr.append(distance(point,p))
        
    df_temp = pd.DataFrame(X)
    df_temp['y'] = y
    df_temp['dist'] = arr
        
        
    return df_temp.sort_values('dist')

In [12]:
for point in X_test.values:
    print(point)
    dist = dist_array(point, X_train.values, y_train.values)
    

[6.4 2.8 5.6 2.1]
[7.6 3.  6.6 2.1]
[4.8 3.1 1.6 0.2]
[6.4 3.1 5.5 1.8]
[5.1 3.5 1.4 0.3]
[4.4 2.9 1.4 0.2]
[5.7 2.6 3.5 1. ]
[5.5 2.4 3.8 1.1]
[5.1 3.5 1.4 0.2]
[5.8 2.7 4.1 1. ]
[6.1 3.  4.6 1.4]
[7.9 3.8 6.4 2. ]
[6.6 2.9 4.6 1.3]
[6.3 3.3 6.  2.5]
[7.7 2.6 6.9 2.3]
[5.4 3.9 1.7 0.4]
[5.7 3.  4.2 1.2]
[7.2 3.  5.8 1.6]
[6.3 2.9 5.6 1.8]
[5.8 2.6 4.  1.2]
[5.5 3.5 1.3 0.2]
[5.  3.5 1.6 0.6]
[6.4 2.7 5.3 1.9]
[5.1 3.4 1.5 0.2]
[6.4 3.2 5.3 2.3]
[6.3 2.8 5.1 1.5]
[5.6 2.8 4.9 2. ]
[5.4 3.4 1.7 0.2]
[6.2 2.2 4.5 1.5]
[6.3 2.5 5.  1.9]
[4.4 3.  1.3 0.2]
[5.8 2.7 3.9 1.2]
[5.5 2.5 4.  1.3]
[4.9 3.  1.4 0.2]
[6.4 2.9 4.3 1.3]
[4.6 3.4 1.4 0.3]
[4.9 3.1 1.5 0.2]
[5.6 2.5 3.9 1.1]
[5.1 3.8 1.9 0.4]
[5.2 2.7 3.9 1.4]
[6.5 3.  5.2 2. ]
[5.6 3.  4.5 1.5]
[4.9 2.4 3.3 1. ]
[7.3 2.9 6.3 1.8]
[6.9 3.1 5.4 2.1]
[6.3 3.4 5.6 2.4]
[7.1 3.  5.9 2.1]
[6.9 3.2 5.7 2.3]
[4.6 3.1 1.5 0.2]
[5.9 3.  5.1 1.8]
[6.  2.9 4.5 1.5]
[6.2 3.4 5.4 2.3]
[6.7 3.1 5.6 2.4]
[6.4 2.8 5.6 2.2]
[4.6 3.6 1.  0.2]
[7.  3.2 4

In [13]:
X_test

sepal length  sepal width  petal length  petal width
128           6.4          2.8           5.6          2.1
105           7.6          3.0           6.6          2.1
30            4.8          3.1           1.6          0.2
137           6.4          3.1           5.5          1.8
17            5.1          3.5           1.4          0.3
..            ...          ...           ...          ...
14            5.8          4.0           1.2          0.2
76            6.8          2.8           4.8          1.4
90            5.5          2.6           4.4          1.2
113           5.7          2.5           5.0          2.0
45            4.8          3.0           1.4          0.3

[120 rows x 4 columns]

In [14]:
dist.shape

(29, 6)

In [15]:
dist.head()

0    1    2    3  y      dist
0   4.8  3.0  1.4  0.1  0  0.200000
19  4.8  3.4  1.6  0.2  0  0.458258
6   4.9  3.6  1.4  0.1  0  0.640312
24  4.8  3.4  1.9  0.2  0  0.648074
20  5.2  3.5  1.5  0.2  0  0.655744

In [16]:
def classification(df_temp, k):
    class_votes = {}
    df_temp2 = df_temp.head(k)
    data = df_temp2.values
    
    number_of_classes = len(np.unique(y))
    for typeclass in range(number_of_classes):
        class_votes[typeclass] = 0
    
    
    for row in data:
        class_ = int(row[4])
        weight = (1 / ((row[5]) + 1e-10))
        class_votes[class_] += weight
    
    return max(class_votes, key=class_votes.get)


**Just Printing the loop to check the data** 

In [17]:
class_votes = {}
df_temp2 = dist.head(3)
data = df_temp2.values

In [18]:
data

array([[4.8       , 3.        , 1.4       , 0.1       , 0.        ,
        0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       , 0.        ,
        0.45825757],
       [4.9       , 3.6       , 1.4       , 0.1       , 0.        ,
        0.64031242]])

In [19]:
number_of_classes = len(np.unique(y))
for typeclass in range(number_of_classes):
    class_votes[typeclass] = 0

In [20]:
class_votes

{0: 0, 1: 0, 2: 0}

In [21]:
for row in data:
    class_ = (int(row[4]))
    print(class_)
    print((row[5]))
    weight = 1 / row[5]
    print(weight)
    class_votes[class_] += weight

0
0.19999999999999998
5.0
0
0.45825756949558394
2.182178902359924
0
0.640312423743285
1.5617376188860603


In [22]:
class_votes

{0: 8.743916521245984, 1: 0, 2: 0}

**End of it** 

# 3. Evaluation:

In [23]:
def KNN_classification(X_train, y_train, X_test, y_test, k):
    preds = []

   
    for point in X_test.values:

        dist = dist_array(point, X_train.values, y_train.values)
        class_ = classification(dist, k)
        preds.append([class_])
    predictions = pd.Series([pred[0] for pred in preds])
    
    accuracy = accuracy_score(predictions, y_test)
    precision = precision_score(predictions, y_test, average='weighted')
    recall = recall_score(predictions, y_test, average='weighted')
    
    
    
    return accuracy, precision, recall

**Precision : Of all positive predictions, how many are really positive**

**formula : (true positive / (true positive + false positive))**

**recall : of all the real positive cases, how many are predicted positive**

**formula : ((true postive)/(true positive + false negative))**

# Result for k = 3

In [24]:
result = KNN_classification(X_train, y_train, X_test, y_test, 3)

In [25]:
print("Accuracy of the Algorithm : ", result[0])
print("Precision for Algorithm  : ", result[1])
print("Recall of Algorithm : ", result[2])

Accuracy of the Algorithm :  0.925
Precision for Algorithm  :  0.9298076923076924
Recall of Algorithm :  0.925


# Result for k = 1

In [26]:
result_1 = KNN_classification(X_train, y_train, X_test, y_test, 1)

In [27]:
print("Accuracy of the Algorithm : ", result_1[0])
print("Precision for Algorithm  : ", result_1[1])
print("Recall of Algorithm : ", result_1[2])

Accuracy of the Algorithm :  0.9333333333333333
Precision for Algorithm  :  0.9363858363858364
Recall of Algorithm :  0.9333333333333333


# Result for k = 5

In [28]:
result_5 = KNN_classification(X_train, y_train, X_test, y_test, 5)

In [29]:
print("Accuracy of the Algorithm : ", result_5[0])
print("Precision for Algorithm  : ", result_5[1])
print("Recall of Algorithm : ", result_5[2])

Accuracy of the Algorithm :  0.9333333333333333
Precision for Algorithm  :  0.9363858363858364
Recall of Algorithm :  0.9333333333333333


# Result for k = 7

In [30]:
result_7 = KNN_classification(X_train, y_train, X_test, y_test, 7)

In [31]:
print("Accuracy of the Algorithm : ", result_7[0])
print("Precision for Algorithm  : ", result_7[1])
print("Recall of Algorithm : ", result_7[2])

Accuracy of the Algorithm :  0.925
Precision for Algorithm  :  0.9410714285714286
Recall of Algorithm :  0.925
